version: 2

builds:
  - env:
      - CGO_ENABLED=0
    main: main.go
    ldflags: '-s -w -X github.com/sensu-community/sensu-plugin-sdk/version.build={{.Version}} -X github.com/sensu-community/sensu-plugin-sdk/version.commit={{.Commit}} -X github.com/sensu-community/sensu-plugin-sdk/version.date={{.Date}}'
    binary: bin/{{ .ProjectName }}
    targets:
      - linux_amd64
      - linux_arm64

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_sha512-checksums.txt"
  algorithm: sha512

archives:
  - id: tar
    formats:
      - tar.gz
    files:
      - LICENSE
